#!/bin/sh
#
# ptolemy scheduled
#
# chkconfig: 2345 95 02
# description:  Run provisiond at boot time to provide an authorisation service for tasks
#              

# Source function library.
. /etc/rc.d/init.d/functions

PROG="ptolemy"
NAME="watcher"
COMMAND="dns_reporter"
USER="netmon"
GROUP="sf"

PIDDIR="/var/run/$PROG/"
pidfile="$PIDDIR/$NAME-$COMMAND.pid"
lockfile="/var/lock/subsys/$PROG-$NAME-$COMMAND"
mkdir -p $PIDDIR
chown -R $USER $PIDDIR
chgrp -R $GROUP $PIDDIR
chmod -R u+rwx $PIDDIR
WORK_DIR='/opt/ptolemy'
PTOLEMY="${WORK_DIR}/bin/ptolemy.py"
LOGFILE="${WORK_DIR}/var/log/${NAME}-${COMMAND}.log"
OPTIONS=" --logfile=${LOGFILE} --pidfile=${pidfile} --uid=${USER} --gid=${GROUP}"

STOP_TIMEOUT=60

start(){
    echo -n $"Starting $PROG $NAME $COMMAND"
    $PTOLEMY $NAME $COMMAND $OPTIONS
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}
    return $RETVAL
}

stop(){
    echo -n $"Stopping $PROG $NAME $COMMAND "
    killproc -p ${pidfile} -d $STOP_TIMEOUT 
    RETVAL=$?
    echo
    rm -f ${pidfile} ${lockfile}
    return $RETVAL
}

reload(){
    echo "Reloading $PROG $NAME $COMMAND "
    killproc -p ${pidfile} $PTOLEMY -HUP 
}

currentstatus(){
    status -p ${pidfile} -l ${lockfile}
}


forcestop(){
    echo "Force stopping $PROG $NAME $COMMAND "
    if [ $COMMAND=="" ]; then
        ps wx -U $USER | grep $PROG | grep $NAME | awk '{print $1}' | xargs kill -9 
    else
        ps wx -U $USER | grep $PROG | grep $NAME | grep $COMMAND | awk '{print $1}' | xargs kill -9 
    fi
    rm -f ${pidfile} ${lockfile}
}

case "$1" in
  start)
    start
        ;;
  stop)
    stop
        ;;
  forcestop)
    forcestop
        ;;
  status)
    currentstatus
        ;;
  reload)
    reload
        ;;
  restart)
    stop
    start
        ;;
  *)
        echo "Usage: $NAME {start|stop|status|restart|reload}"
        exit 1
esac

exit 0
