#!/bin/sh
#
# ptolemy stored redis
#
# chkconfig: 2345 95 02
# description:  Run ptolemy stored redis
#              

# Source function library.
. /etc/rc.d/init.d/functions

PROG="ptolemy"
NAME="stored"
COMMAND="redis"
USER="netmon"
GROUP="sf"

WORK_DIR='/opt/ptolemy'
. /opt/ptolemy/etc/init.d/ptolemy-rc